name: 'Tag Mapper'
description: 'Map tags to numbers'
inputs:
  tag-name:
    description: 'Github tag'
    required: true
outputs:
  user-number:
    description: 'User account number'
    value: ${{ steps.mapper.outputs.user-number }}
runs:
  using: "composite"
  steps:
    - id: mapper
      run: ${{ github.action_path }}/get_user.sh ${{ inputs.tag-name }}
      shell: bash
      env:
        DEV_ENV: ${{ secrets.DEV_ENV }}
        TST_ENV: ${{ secrets.TST_ENV }}
        ACC_ENV: ${{ secrets.ACC_ENV }}
        PRD_ENV: ${{ secrets.PRD_ENV }}