name: 'Tag Mapper'
description: 'Map tags to numbers'
inputs:
  tag-name:
    description: 'Github tag'
    required: true
outputs:
  user-number:
    description: 'User account number'
    value: ${{ steps.mapper.outputs.user-id }}
runs:
  using: "composite"
  steps:
    - id: mapper
      run: ${{ github.action_path }}/get_user.sh ${{ inputs.tag-name }}
      shell: bash